F03
dimitrivitulin/crazee-burger pull request #3
Opened 2023-01-26 10:30 UTC by dimitrivitulin

2023-01-26 15:06 UTC, simoncdn commented on src/components/pages/login/LoginPage.js
> +    background-blend-mode: darken;
Tu as un problème sur l'effet Dark du ton background, je pense que cela vient du fait que tu ne définis pas de background-color qui devrait etre de : rgba(0, 0, 0, 0.7);

2023-01-26 15:23 UTC, simoncdn commented on src/components/reusable-ui/PrimaryButton.js
> +  font-weight: ${theme.weights.medium};
Il me semble que le weight utilité pour la fonts et le heavy

2023-01-26 15:23 UTC, simoncdn commented on src/components/pages/login/LoginForm.js
> +    line-height: 3em;
Il te manque le padding : 30px 50px; 
et tu peux enlever le line-height ici

2023-01-26 20:15 UTC, vileaddev requested changes
Quelque rectifs sur le naming de variable mais sinon c'est du bon code ! 👏 🎈 

Je te laisse changer et re-git push tout ça et quand c'est bon, je te validerai ta PR 😉

2023-01-26 20:15 UTC, vileaddev commented on src/components/pages/login/LoginPage.js
> +    <LoginPageWrapper>
```suggestion
    <LoginPageStyled>
```

Pas la peine de préciser Wrapper, on le sait déjà. En revanche, ce qu'on ne sait pas, c'est que c'est en fait un Styled-Component. Le bon usage qu'on retrouve en entreprise c'est de rajouter "Styled" ici.

Par ailleurs, "LoginPageWrapper" laisse penser que c'est un composant à part entière qu'on peut retrouver dans components/reusable-ui alors que ce n'est pas le cas. C'est uniquement un Styled-Component.

2023-01-26 20:15 UTC, vileaddev commented on src/components/pages/login/LoginPage.js
> +const LoginPageWrapper = styled.div`
```suggestion
const LoginPageStyled = styled.div`
```

2023-01-26 20:15 UTC, vileaddev commented on src/components/reusable-ui/Logo.js
> +    <LogoWrapper>
```suggestion
    <LogoStyled>
```

Pareil ici.

2023-01-26 20:15 UTC, vileaddev commented on src/components/reusable-ui/PrimaryButton.js
> +    <PrimaryButtonStyled type="submit">
```suggestion
    <PrimaryButtonStyled >
```

Ici, on est dans le cadre d'un composant réutilisable qui ne va pas forcément être utilisé dans un form. Donc lui assigner d'emblée l'attribut type="submit", c'est ajouter du spécifique dans un composant réutilisable et donc générique.

2023-01-26 21:02 UTC, dimitrivitulin commented on src/components/pages/login/LoginForm.js
> +    line-height: 3em;
Ok j'ai fait les changements

2023-01-27 07:04 UTC, vileaddev approved these changes
Beau boulot ! C'est parfait pour moi, tu peux merge ✅ 😉

2023-01-27 07:08 UTC, merged